name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Diego0160
          outputs: |
            output/snake.svg?color_snake=#7EBAE4&color_dots=#161b22,#2ea043,#44A51C,#7EBAE4,#58a6ff
            output/snake-dark.svg?palette=github-dark
            output/snake.gif?color_snake=#7EBAE4&color_dots=#161b22,#2ea043,#44A51C,#7EBAE4,#58a6ff&color_background=#0d1117

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
